/**
 * Verified counties — the ~730 county portals confirmed scrapable by the discovery
 * run (verified_ok). The Testing Console only lets you pick from these: if a county
 * isn't here, it hasn't been verified. Generated by scripts/build-verified-counties.mjs.
 *
 * Search/match logic mirrors lib/usCounties.ts, but over the verified subset only.
 */
import verified from '@beaver/shared-data/verified_counties.json';

export interface VerifiedCounty {
  county_id: string;
  label: string;
  state: string;
  url: string;
  platform: string | null;
}

const counties: VerifiedCounty[] = (verified as VerifiedCounty[])
  .slice()
  .sort((a, b) => a.label.localeCompare(b.label));

const byLabel = new Map(counties.map((c) => [c.label, c]));

export const VERIFIED_COUNTY_COUNT = counties.length;

export function isVerifiedCounty(label: string): boolean {
  return byLabel.has(label.trim());
}

/** Portal URL to scrape for a verified county label, or null if not verified. */
export function verifiedCountyUrl(label: string): string | null {
  return byLabel.get(label.trim())?.url ?? null;
}

function normalizeForSearch(value: string): string {
  return value.toLowerCase().replace(/\s+/g, ' ');
}

export function searchVerifiedCounties(query: string, limit = 8): string[] {
  const q = normalizeForSearch(query.trim());
  if (!q) return [];

  const prefix: string[] = [];
  const substring: string[] = [];

  for (const county of counties) {
    const normalized = normalizeForSearch(county.label);
    if (normalized.startsWith(q)) {
      prefix.push(county.label);
    } else if (normalized.includes(q)) {
      substring.push(county.label);
    }
    if (prefix.length + substring.length >= limit * 2) break;
  }

  return [...prefix, ...substring].slice(0, limit);
}
