#!/usr/bin/env bash
# Install/start Ollama, pull Qwen 2.5 7B model, write .env.local for local pipeline.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "==> Beaver local Qwen 2.5 7B setup"

if ! command -v ollama &>/dev/null; then
  echo "Ollama not found — installing..."
  INSTALLED=false
  if command -v brew &>/dev/null; then
    if brew install ollama 2>/dev/null; then
      INSTALLED=true
    else
      echo "Homebrew install failed — trying official Ollama installer..."
    fi
  fi
  if [ "$INSTALLED" = false ] && ! command -v ollama &>/dev/null; then
    curl -fsSL https://ollama.com/install.sh | sh
  fi
fi

if ! command -v ollama &>/dev/null; then
  echo ""
  echo "ERROR: Ollama is not installed."
  echo "Install manually: https://ollama.com/download"
  echo "Then re-run: pnpm qwen:setup"
  exit 1
fi

if ! curl -sf http://localhost:11434/api/tags &>/dev/null; then
  echo "Starting Ollama server..."
  ollama serve &>/dev/null &
  for _ in $(seq 1 30); do
    if curl -sf http://localhost:11434/api/tags &>/dev/null; then
      break
    fi
    sleep 1
  done
fi

if ! curl -sf http://localhost:11434/api/tags &>/dev/null; then
  echo "ERROR: Ollama did not start on http://localhost:11434"
  exit 1
fi

RAM_BYTES="$(sysctl -n hw.memsize 2>/dev/null || echo 8589934592)"
RAM_GB=$((RAM_BYTES / 1024 / 1024 / 1024))
if [ "$RAM_GB" -ge 12 ]; then
  MODEL="qwen2.5:7b"
else
  MODEL="qwen2.5:3b"
fi

echo "Detected ~${RAM_GB}GB RAM — pulling model: $MODEL"
ollama pull "$MODEL"

cat > .env.local <<EOF
# Auto-generated by scripts/setup-qwen.sh — do not commit
LLM_MOCK_MODE=false
LLM_ENDPOINT_URL=http://localhost:11434/v1/chat/completions
LLM_API_KEY=ollama
LLM_MODEL=${MODEL}
SCRAPER_REAL=true
USE_DOCLING=true
MOCK_MODE=false
MATCH_MIN_RELEVANCE=0.5
MATCH_MAX_PER_PROJECT=10
LOCAL_MAX_DOCS_PER_COUNTY=3
BEAVER_ERROR_LOG=local-run/errors.ndjson
EOF

echo "Wrote .env.local (model=${MODEL})"

echo "==> Verifying Ollama chat endpoint..."
RESPONSE="$(curl -sf http://localhost:11434/v1/chat/completions \
  -H 'Content-Type: application/json' \
  -d "{\"model\":\"${MODEL}\",\"messages\":[{\"role\":\"user\",\"content\":\"Reply with only the word ok\"}],\"temperature\":0}")"

if echo "$RESPONSE" | grep -q '"content"'; then
  echo "Ollama OK — local Qwen is ready."
else
  echo "WARNING: unexpected Ollama response: $RESPONSE"
  exit 1
fi

echo ""
echo "Next: pnpm local:run"
